# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mli < Formula
  desc "Manage macOS Login Items"
  homepage "https://github.com/5ouma/mli"
  version "0.4.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/5ouma/mli/releases/download/v0.4.1/mli_Darwin_x86_64.tar.gz"
    sha256 "716834ed29bbf9c8913c7839e9444ef749f7024d19dd0bc2eac7b2eac1aca59b"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/5ouma/mli/releases/download/v0.4.1/mli_Darwin_arm64.tar.gz"
    sha256 "063ed2e73eda9eaf9005dfe51d4560023bd0c081a22fc68d8cdbd42ea92b7fa7"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end

  test do
    system "#{bin}/#{name}", "-v"
  end
end
