# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mli < Formula
  desc "Manage macOS Login Items"
  homepage "https://github.com/5ouma/mli"
  version "0.4.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/5ouma/mli/archive/refs/tags/v0.4.2.tar.gz"
    sha256 "a66d5079b7fc888ef7504bc0ee46c81db5b6f7e557b4a822a39ead2bd2b75dc2"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/5ouma/mli/releases/download/v0.4.1/mli_Darwin_arm64.tar.gz"
    sha256 "063ed2e73eda9eaf9005dfe51d4560023bd0c081a22fc68d8cdbd42ea92b7fa7"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end

  test do
    system "#{bin}/#{name}", "-v"
  end
end
