# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mli < Formula
  desc "Manage macOS Login Items"
  homepage "https://github.com/5ouma/mli"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/5ouma/mli/releases/download/v0.3.0/mli_Darwin_arm64.tar.gz"
    sha256 "8fe0d2fdf94ee30d68f5632385aa6888612acf1d0eb01a389741f1b170058f02"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/5ouma/mli/releases/download/v0.3.0/mli_Darwin_x86_64.tar.gz"
    sha256 "201b7c628308e47a21d3650c53de0de4fa3c9eddd5e5ff8404ca182033f2d89b"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end

  test do
    system "#{bin}/#{name}", "-v"
  end
end
